#!/usr/bin/env php
<?php
define('APP_START', microtime(true));
require __DIR__ . '/vendor/autoload.php';
$app = require_once __DIR__ . '/bootstrap/app.php';
$console = $app->make(App\Console\ConsoleKernel::class);
$console->start();
